package com.spa.urbanstep

enum class ListType {
    HEAD_LIST, SUB_HEAD_LIST, CATEGORY, SUB_CATEGORY, ZONE, WARD, COLONY, TOPIC, PROBLEM,AUTHORITY,UPDATE_US_CATEGORY,UPDATE_US_SUB_CATEGORY,UPDATE_US_MASTER_LIST
}